version: '3.5'

services:
  skywalker:
    tty: true
    build: 
      context: .
    container_name: skywalker #指定容器名
    ports: 
      - 7001:7001
    environment:
      - SET_CONTAINER_TIMEZONE=true #指定容器运行所属时区
      - CONTAINER_TIMEZONE=Asia/Shanghai
    volumes:
      - /data/auto_sign/config:/app/config    
      - /data/auto_sign/logs:/app/logs
